In [23]:
import torch
A = torch.randint(10,(20,)) -5
A = A.reshape(2,2,5)
# print(A)
P = A>0
print(P)
# print((torch.sum(P,dim=(-1,-2))))
P = P/(torch.sum(P,dim=(-1,-2),keepdim=True))
dist = torch.distributions.Categorical(probs=P.reshape(2,-1))
print(P)
Sa = dist.sample((5,))
# 把sample变换回原来的形状
# (9,1) = ( (1,4),(0,1) )

Re = Sa // 5
Co = Sa % 5
print(Sa)
print(Re,Co)

tensor([[[False,  True, False, False, False],
         [False,  True,  True,  True,  True]],

        [[False,  True,  True, False,  True],
         [False, False,  True, False,  True]]])
tensor([[[0.0000, 0.2000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.2000, 0.2000, 0.2000, 0.2000]],

        [[0.0000, 0.2000, 0.2000, 0.0000, 0.2000],
         [0.0000, 0.0000, 0.2000, 0.0000, 0.2000]]])
tensor([[1, 4],
        [1, 7],
        [8, 7],
        [9, 4],
        [9, 4]])
tensor([[0, 0],
        [0, 1],
        [1, 1],
        [1, 0],
        [1, 0]]) tensor([[1, 4],
        [1, 2],
        [3, 2],
        [4, 4],
        [4, 4]])


In [37]:
import torch
mask = torch.tensor([[0],[1]],dtype = torch.float32)
print(mask.shape)
A = torch.randint(10,(20,)) -3
A = A.reshape(2,1,2,5)
# print(A)
print(A>0)
P = torch.as_tensor((A>0).to(torch.float32), dtype=torch.float32)
print(P)

sample = torch.multinomial(P.reshape(2,-1), 1)
# print(sample)
print(sample//5,"\n", sample%5)
print(sample.shape)
P[torch.arange(2).reshape(-1,1),0, sample//5, sample%5] += mask
print(P)

torch.Size([2, 1])
tensor([[[[ True, False,  True,  True,  True],
          [False,  True, False,  True, False]]],


        [[[ True, False, False,  True, False],
          [False,  True, False, False,  True]]]])
tensor([[[[1., 0., 1., 1., 1.],
          [0., 1., 0., 1., 0.]]],


        [[[1., 0., 0., 1., 0.],
          [0., 1., 0., 0., 1.]]]])
tensor([[1],
        [1]]) 
 tensor([[1],
        [1]])
torch.Size([2, 1])
tensor([[[[1., 0., 1., 1., 1.],
          [0., 1., 0., 1., 0.]]],


        [[[1., 0., 0., 1., 0.],
          [0., 2., 0., 0., 1.]]]])


In [13]:
torch.zeros((5,)).dtype

torch.float32

In [41]:
torch.randint(5,(20,)).reshape(10,2) == 0

tensor([[False, False],
        [ True, False],
        [False,  True],
        [False, False],
        [False,  True],
        [False,  True],
        [False, False],
        [False, False],
        [False, False],
        [False, False]])

In [76]:
import torch.nn.functional as F
size=  5
N = 9
EPS=1e-6
s = torch.randint(5,(N,3,size,size),dtype=torch.float32)
# torch.sum(s[:,0],dim=(-1,-2),keepdim=False)[:,None].shape
# (torch.abs(torch.sum(s[:,0],dim=(-1,-2),keepdim=False)[:,None])<EPS).shape
act = torch.randint(4,(N,1),dtype=torch.int64)
# act = torch.tensor([1,2,3])
# print(act,act.shape,act.dtype)
print(F.one_hot(act,num_classes=4).shape)
_move_kernel =torch.concat([
            torch.tensor([[0,0,0],[1,0,0],[0,0,0]],dtype=torch.float32).flip(dims=(-2,-1)).reshape(1,1,3,3),
            torch.tensor([[0,0,0],[0,0,1],[0,0,0]],dtype=torch.float32).flip(dims=(-2,-1)).reshape(1,1,3,3),
            torch.tensor([[0,1,0],[0,0,0],[0,0,0]],dtype=torch.float32).flip(dims=(-2,-1)).reshape(1,1,3,3),
            torch.tensor([[0,0,0],[0,0,0],[0,1,0]],dtype=torch.float32).flip(dims=(-2,-1)).reshape(1,1,3,3),
        ])
next_head = torch.conv2d(s[:,:1], 
                                    _move_kernel,
                                    padding=1)
one_hot_act = F.one_hot(act,num_classes=4).to(torch.float32)
print(next_head.shape,one_hot_act.shape)
next_head = torch.einsum('ijkl,iaj->ikl',next_head,one_hot_act)
print(next_head.shape)


hit_body = torch.sum(next_head*s[:,2],dim=(-1,-2),keepdim=False)>0
print(hit_body.shape)
# F.one_hot(torch.tensor([1,2,3]).reshape(-1,1),num_classes=4).shape
# torch.tensor([1,2,3]).reshape(-1,1).shape
# print(next_head.shape)

torch.Size([9, 1, 4])
torch.Size([9, 4, 5, 5]) torch.Size([9, 1, 4])
torch.Size([9, 5, 5])
torch.Size([9])


In [82]:
torch.logical_or(torch.tensor(1.0),torch.tensor(0.))

tensor(True)